solve #98 footer is not responsive issue
NJACKWinterOfCode/NJACKWinterOfCode.github.io pull request #104
Opened 2021-01-09 06:26 UTC by Vishal-raj-1

### Issue Fix
Fixes #98 

**Description of changes made** 
Earlier it was overflowed as mentioned it #98 . for making it responsive what I have done is, I have adding the background color to footer so that it will not overflow now.

**Submissions guide:**

- [ ] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [ ] Have you lint your code locally prior to submission?

@s-ayush2903 @Ankit7Das Please look at this PR after merging this #102 one!!

2021-01-09 11:29 UTC, s-ayush2903 requested changes
For the issue this PR targets, we need only the latest commit of this PR as of now, right now you have very old commits from your old branches, you should delete 'em and force push the branch here. Here, you'll need to use `reset --hard HEAD` for deleting irrelevant commits in this branch, although this is a very dangerous command, but this'll do the trick needed. Read about it [here](https://git-scm.com/docs/git-reset)

2021-01-09 11:53 UTC, Vishal-raj-1 commented on contact.html
> +      });
these braces are missing. I have debug that issue from my console.

2021-01-09 11:57 UTC, Vishal-raj-1 commented
> For the issue this PR targets, we need only the latest commit of this PR as of now, right now you have very old commits from your old branches, you should delete 'em and force push the branch here. Here, you'll need to use `reset --hard HEAD` for deleting irrelevant commits in this branch, although this is a very dangerous command, but this'll do the trick needed. Read about it [here](https://git-scm.com/docs/git-reset)

No no Sir !! I know this commits message is shown till my branch  is not updated with master branch of this repo. doing `git pull upstream master` and `git push` works here. 

@s-ayush2903 this is fine now !! check it

2021-01-09 17:43 UTC, s-ayush2903 requested changes
The text now overlaps with the back to top button, this should be fixed

2021-01-09 18:05 UTC, Vishal-raj-1 commented
> The text now overlaps with the back to top button, this should be fixed

It's done.

2021-01-17 14:14 UTC, Vishal-raj-1 commented
> It's done.

Any Updates @s-ayush2903 ??

2021-01-17 14:42 UTC, s-ayush2903 commented
Ah, it is clean, will merge it now. Was busy in college these days, thanks for pinging :+1:

2021-01-17 14:45 UTC, Vishal-raj-1 commented
> Ah, it is clean, will merge it now. Was busy in college these days, thanks for pinging 👍

No Problem !!

2021-01-17 14:45 UTC, s-ayush2903 approved these changes
LGTM

2021-01-17 14:45 UTC, merged