Fix alignment in leaderboard (responsively)
NJACKWinterOfCode/NJACKWinterOfCode.github.io pull request #78
Opened 2020-12-26 06:53 UTC by paramsiddharth

# Fix alignment in leaderboard (responsively)
Resolves #77: **Fix alignment on participants**

## Modifications
- `style.css` modified to fix width of each column in the table.
- The positions are aligned to the right within the first column.
- The names start from the same distance from the left in each row.
- The scores are aligned to the right.
- The final version is made responsive using `@media` queries.

## Comparison
- Previous format:
  | Desktop | Mobile |
  |---|---|
  |  ![image](https://user-images.githubusercontent.com/30315706/103146826-c3b30580-4774-11eb-98ac-a9077095e637.png)  | ![image](https://user-images.githubusercontent.com/30315706/103146830-dd544d00-4774-11eb-9502-ec6cad23013b.png)  |
- New format:
  | Desktop | Mobile |
  |---|---|
  |  ![image](https://user-images.githubusercontent.com/30315706/103146841-04ab1a00-4775-11eb-9779-0575010c064d.png)  |  ![image](https://user-images.githubusercontent.com/30315706/103146853-18ef1700-4775-11eb-99a5-b655b4a6c5d3.png) |

2020-12-26 11:12 UTC, s-ayush2903 requested changes
@paramsiddharth We don't want the positions and scores to be constrained to the extreme right, they(including handles) should be in proper alignment with their column titles

2021-01-04 17:45 UTC, s-ayush2903 commented
@paramsiddharth Are you able to work on this PR further?

2021-01-05 06:04 UTC, paramsiddharth commented
> @paramsiddharth Are you able to work on this PR further?

@s-ayush2903 Yes, I'll finish it soon.

2021-07-02 10:29 UTC, ashwaniYDV commented
hi @paramsiddharth 
Is this PR ready to be merged?

2021-07-02 16:25 UTC, paramsiddharth commented
> hi @paramsiddharth
> Is this PR ready to be merged?

No, @ashwaniYDV . I am not working on it at the moment.

2021-07-02 16:25 UTC, closed without merging