Icons updated in 2019 statistics section
NJACKWinterOfCode/NJACKWinterOfCode.github.io pull request #80
Opened 2020-12-27 12:26 UTC by yash0501

Icons updated in 2019 statistics section ( Solved issue #74 )

2020-12-27 12:40 UTC, s-ayush2903 requested changes
Change the projects icon to the repo icon that github uses

2020-12-27 12:40 UTC, s-ayush2903 commented on debug.log
> +[1227/155125.116:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
We don't need to commit this file

2020-12-27 13:13 UTC, s-ayush2903 commented
Now it looks a weird, it has an odd size which makes it look different from the other icons, can you fix it. I'm talking about the length of the projects cards that is lesser than that of others. Have a look. You may check by the deployment made by vercel to see it
|Uneven card Size|
|--|
|![weird](https://user-images.githubusercontent.com/56556919/103171527-0a872500-4873-11eb-95a4-ff3b80bac0dc.png)|

2020-12-27 13:18 UTC, s-ayush2903 approved these changes
Good Work and thanks for making the changes quickly :+1:

2020-12-27 13:18 UTC, merged

2020-12-27 13:19 UTC, yash0501 commented
Thank you for making me aware of the bugs in PR.

2020-12-29 11:04 UTC, s-ayush2903 commented
@yash0501 can you please update the icon for PRs, it would be better if we show the icon that github uses for showing the _merged_ PRs, means the one which you can see after your PR has been merged up here. I don't think you would need five points for it